### ISSUE TITLE
linux build

### ISSUE THREAD

**Issue by huglester** [palginpav/hsrminer#10]
Hello
are there any plans to have linux build as well?

**Comment by DrStein99** [comment]
I am also interested in this.  I prefer to use linux.  It's way easier for me to SSL into my servers attached in the freezing cold garage, instead of using slow windows remote GUI software.

**Comment by amg81** [comment]
This would be a very nice thing so I can try out your miner.  Currently run Windows for personal computer but Linux for anything techie...

**Comment by goodthebest** [comment]
No version for Linux/Ubuntu?

**Comment by goodthebest** [comment]
@palginpav any plans for linux hsrminer?

**Comment by LiChengxin007** [comment]
哪里开源了,一个代码都看不到

**Comment by devMagics** [comment]
+1

**Comment by palginpav** [comment]
hsrminer is obsolete for now, there will be no future developement on current version. It'll get back rebranded and reworked, with full *nix support, but can't tell when this'll happen, exactly not the nearest future, maybe winter 2018/2019
