### ISSUE TITLE
The overall speed reported very rarely in the NeoScrypt version

### ISSUE THREAD

**Issue by borzaka** [palginpav/hsrminer#11]
The first overall speed was reported after ~6 minutes of starting.
This script has been used by [MultiPoolMiner](https://github.com/MultiPoolMiner/MultiPoolMiner), and without an API, they are rely on screen reading, and find for any speed related text. If their screenreader (PowerShell) doesn't find any speed related text, it closes the script (and marks as failed), and opens the next fastest miner.

So, can you report the overall speed more often? :) It would be nice before the release of the API version. Thank you.

Your script is the fastest NeoScrypt miner in the known Universe ;) Thank you for your work!

**Comment by station384** [comment]
Just poked my nose in here and see I have the same issue as you.

**Comment by palginpav** [comment]
Sorry, software is obsolete and no future developement on this one will be done. You'll need to wait till winter 2018/2019, or better use another miner :)
