### ISSUE TITLE
Doesn't work on Titan X (pascal)

### ISSUE THREAD

**Issue by luxferro** [palginpav/hsrminer#12]
The miner doesn't like Titan X pascal at all, even at stock clocks.

I get the following:

 INFO : [22:50:58] : Securing devfee mining...
 INFO : [22:50:58] : Dev_Main OK.
 INFO : [22:50:58] : Dev_Backup OK.
 INFO : [22:50:58] : Dev pools checked, at least 1 accessible, continue...
 INFO : [22:50:58] : POOL: stratum+tcp://neoscrypt.usa.nicehash.com:3341
 INFO : [22:50:58] : Checking for NVML...
 INFO : [22:50:58] : NVML monitoring enabled, continue...
 INFO : [22:50:58] : 1 GPU found/specified, initializing miner...
 INFO : [22:50:59] : Share difficulty reset -- 4096 (0.06250)
 INFO : [22:50:59] : New block #32746 received, new difficulty is 690.362
 INFO : [22:50:59] : GPU #0: TITAN X (Pascal), flags: 0, 0, 0
 INFO : [22:50:59] : submit_upstream_work stratum_send_line failed
 INFO : [22:50:59] : ...retry after 10 seconds
 INFO : [22:50:59] : Share Rejected, Share above target.
...
*repeat a bunch of times*
...
 INFO : [22:50:59] : Share Rejected, Share above target.
 INFO : [22:50:59] : Connection interrupted
 INFO : [22:51:09] : submit_upstream_work stratum_send_line failed
 INFO : [22:51:09] : ...retry after 10 seconds
 INFO : [22:51:09] : Share Rejected, Job not found.
...
*repeat a bunch of times*
...
 INFO : [22:51:09] : Share Rejected, Job not found.

**Comment by pjdouillard** [comment]
I confirm this too and with 1080 Ti also.

**Comment by palginpav** [comment]
Not working on recent driver. hsrminer is obsolete and no future developement will be done on this code. You'll need to wait until winter 2018/2019, or better use another miner.
