### ISSUE TITLE
Duplicate / Invalid Share

### ISSUE THREAD

**Issue by pfeiflelukas** [palginpav/hsrminer#13]
Hi all,

I have two GTX 970's and i can connect to the pool but all i get are rejected shares. Every now and again some shares do get accepted but then it stops working. I have tried to debug the issue but with no luck so far.

Thanks

**Comment by palginpav** [comment]
hsrminer is obsolete and there will be no future developement on this code. You'll need to wait until winter 2018/2019, but better use another miner :)
