### ISSUE TITLE
Fails with memory allocation failure on NVIDIA 397+

### ISSUE THREAD

**Issue by gradinkov** [palginpav/hsrminer#20]
$title

**Comment by palginpav** [comment]
You need to increase pagefile size to sum of all your GPUs memory amount equivalent and everything'll work fine.

**Comment by gradinkov** [comment]
Nope, it has nothing to do with pagefile, it crashes even with 64G pagefile + 8GB RAM with only 6x1070 (48G VRAM).

It consistently works with anything below 397, and consistently crashes with 397+. And it crashes **instantly**.

Not that this has any relevance now, since HSR has been basically killed. But closing an issue like this is extremely lazy nevertheless.

**Comment by palginpav** [comment]
hsrminer is obsolete right now, no future developement on this code will be done. The only way to prevent this error is to recompile it for newer driver, which won't be done. If you wrote your pagefile info in initial issue opening, I'd give you this answer, but without providing any information, what did you expect?

**Comment by gradinkov** [comment]
I'd expect not being given unjustified assumptions. Because apparently you already knew that the miner is obsolete, still, you assumed it's not the miner's at fault, but my setup. If I don't provide one specific detail, why would you automatically assume it's wrong?

**Comment by palginpav** [comment]
Hm, I can ask you the same, if you somehow came to this miners thread and read the content, you'd probably know that it was dead ~ Feb/Mar 2018. If it worked for you on old driver, you've updated driver and it stopped working, think the case is obvious. Why open issue months after actual death?

**Comment by gradinkov** [comment]
Months after? I've been happily mining and exchanging HSR until this wednesday. The issue was opened 2 months earlier.

**Comment by palginpav** [comment]
In my vision, any software in crypto sphere without updates for even month = dead software. HSR is moving to HC, so think hsrminer in its current variant won't work anymore for any coin in this world. Have a nice day!
