### ISSUE TITLE
 Share Rejected, duplicate share 

### ISSUE THREAD

**Issue by lukiifaz** [palginpav/hsrminer#4]
hsrminer_neoscrypt.exe -o stratum+tcp://hub.miningpoolhub.com:17012 -u lukii.legion -p x
 INFO : [23:05:19] : GPU#0 - GeForce GTX 1060, speed is 8213.82kH/s
and
 INFO : [23:06:06] : Share Rejected, duplicate share 
But balance on feathercoin.miningpoolhub.com is 0

**Comment by pinkzebrus** [comment]
on titan XP not work

**Comment by palginpav** [comment]
Not working on recent drivers, sorry. hsrminer is completely obsolete and won't be developed anymore, you'll need to wait till winter 2018/2019, or better just use another mining software.
