### ISSUE TITLE
Deteriorating Hashrate

### ISSUE THREAD

**Issue by XxMetalMartyrxX** [palginpav/hsrminer#6]
This miner starts off strong, pulling about 6300kh/s on Neoscrypt with 4x 1080s and 1x 1070. The issue I've found is that the hash rate deteriorates over time. Overnight it went from around 6300kh/s to 5800kh/s. Basically puts back in line with the Klaust miner.

**Comment by Bllop** [comment]
Same issue for me!

**Comment by palginpav** [comment]
It's "shown" hashrate or hashrate on pool side? Shown hashrate is calculated the wrong way. Anyway, hsrminer isn't supported anymore and completely obsolete. You'll need to wait until winter 2018/2019, or better just use another miner of your choice :)
