### ISSUE TITLE
"Cuda error in func 'neoscrypt_cpu_hash_1070' at line 1460 : the launch timed out and was terminated."

### ISSUE THREAD

**Issue by MartyEz** [palginpav/hsrminer#9]
I have this error :

"Cuda error in func 'neoscrypt_cpu_hash_1070' at line 1460 : the launch timed out and was terminated."

Pic :
https://ibb.co/e5gAMm

I have 6gpus kfa2 gtx 1070 ex. I am on windows 10 pro updated and nvidia 390.65 drivers.

If someone could help me

SOLVED : Installed 388.3x drivers and not the latest 390

**Comment by palginpav** [comment]
hsrminer is obsolete, not developed anymore and doesn't support any of recent drivers, sorry. You need to wait till winter 2018/2019, or better just use another miner software.
